export const Regions = [
  { Name: 'Lazio', Aree: ['BELMONTE', 'MARCHEGIANI', 'PANACCIONE', 'SORRENTINO', 'VALENTINI', 'VITALE'], BackgroundImage:'Italia.jpg', Avatar: 'Lazio.png' },
  { Name: 'Toscana', Aree: ['BIRELLI', 'BONDI', 'GRILLI', 'POGGIANTI'],BackgroundImage:'Italia.jpg', Avatar: 'Toscana.png' },
  { Name: 'ABRUZZO/UMBRIA/MOLISE', Aree: ['ABRUZZO/UMBRIA/MOLISE', 'DI VITO'],BackgroundImage:'Italia.jpg', Avatar: 'AbruzzoUmbriaMolise.png' },
  { Name: 'MARCHE', Aree: ['CATENA'],BackgroundImage:'Italia.jpg', Avatar: 'Marche.png' },
  { Name: 'VENETO', Aree: ['CONTRERAS', 'VENETO', 'NALIN'],BackgroundImage:'Italia.jpg', Avatar: 'Veneto.png' },
  { Name: 'PUGLIA/BASILICATA', Aree: ['PUGLIA/BASILICATA', 'MANIGRASSO', 'TRISCIUOGLIO'],BackgroundImage:'Italia.jpg', Avatar: 'PugliaBasilicata.png' },
  { Name: 'EMILIA ROMAGNA', Aree: ['EMILIA ROMAGNA'],BackgroundImage:'Italia.jpg', Avatar: 'EmiliaRomagna.png' },
  { Name: 'LIGURIA', Aree: ['LIGURIA', 'DEL NERO'],BackgroundImage:'Italia.jpg', Avatar: 'Liguria.png' },
  { Name: 'SARDEGNA', Aree: ['SARDEGNA'],BackgroundImage:'Italia.jpg', Avatar: 'Sardegna.png' },
  { Name: 'PIEMONTE', Aree: ['PIEMONTE'],BackgroundImage:'Italia.jpg', Avatar: 'Piemonte.png' },
  { Name: 'CALABRIA/SICILIA', Aree: ['CALABRIA/SICILIA', 'NISTICO'],BackgroundImage:'Italia.jpg', Avatar: 'CalabriaSicilia.png' },
  { Name: 'CAMPANIA', Aree: ['PENTANGELO', 'PETRICCIUOLO C.', 'PETRICCIUOLO G.', 'RUOTOLO'],BackgroundImage:'Italia.jpg', Avatar: 'Campania.png' },
  { Name: 'LOMBARDIA', Aree: ['LOMBARDIA', 'SIMONE'],BackgroundImage:'Italia.jpg', Avatar: 'Lombardia.png' },
];


export const Managers = [
  {
    Name: 'Maurizio',
    Surname: 'Contino',
    Role: 'Area manager',
    Area: 'BELMONTE',
    Regions: 'LAZIO',
    Avatar: 'male-04.jpg',
    BackgroundImage: '14-640x480.jpg',
  },
  {
    Name: 'Davide',
    Surname: 'Contino',
    Role: 'Regional manager',
    Area: 'BONDI',
    Regions: 'TOSCANA',
    Avatar: 'male-04.jpg',
    BackgroundImage: '19-640x480.jpg',
  },
  {
    Name: 'Elena',
    Surname: 'Masotti',
    Role: 'Area manager',
    Area: 'ABRUZZO/UMBRIA/MOLISE',
    Regions: 'ABRUZZO/UMBRIA/MOLISE',
    Avatar: 'female-06.jpg',
    BackgroundImage: '34-640x480.jpg',
  },
];
export const Aree = [
  { Name: 'BELMONTE' },
  { Name: 'BIRELLI' },
  { Name: 'BONDI' },
  { Name: 'ABRUZZO/UMBRIA/MOLISE' },
  { Name: 'MARCHE' },
  { Name: 'CONTRERAS' },
  { Name: 'PUGLIA/BASILICATA' },
  { Name: 'VENETO' },
  { Name: 'EMILIA ROMAGNA' },
  { Name: 'LIGURIA' },
  { Name: 'DEL NERO' },
  { Name: 'SARDEGNA' },
  { Name: 'DI VITO' },
  { Name: 'GRILLI' },
  { Name: 'PIEMONTE' },
  { Name: 'MANIGRASSO' },
  { Name: 'MARCHEGIANI' },
  { Name: 'NALIN' },
  { Name: 'NISTICO' },
  { Name: 'LAZIO' },
  { Name: 'PENTANGELO' },
  { Name: 'CALABRIA/SICILIA' },
  { Name: 'PETRICCIUOLO C.' },
  { Name: 'PETRICCIUOLO G.' },
  { Name: 'TOSCANA' },
  { Name: 'LOMBARDIA' },
  { Name: 'RUOTOLO' },
  { Name: 'SIMONE' },
  { Name: 'SORRENTINO' },
  { Name: 'TRISCIUOGLIO' },
  { Name: 'VALENTINI' },
  { Name: 'VITALE' },
];
